name: 'build'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idf_ver: ["release-v5.0", "release-v5.1", "latest"]
        idf_target: ["esp32", "esp32c3"]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build example
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.idf_ver }}
        target: ${{ matrix.idf_target }}
        path: examples/pa1010d-example
